version: "3.9"
services:
  graphql_db:
    image: postgres:16
    container_name: graphql_db_container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pyApiTest
    ports:
      - "5432:5432"
    networks:
      - backend

  migrations:
    build: .
    command: alembic upgrade head
    depends_on:
      graphql_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/pyApiTest
    networks:
      - backend

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - graphql_db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/pyApiTest
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
