version: "3.9"

services:
  api:
    build: .
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pyApiTest
    ports:
      - "5432:5432"

  migrations:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    command: alembic upgrade head
